services:
  # Backend Socket.IO Service
  - type: web
    name: typerightr-socketio
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && node server.cjs
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: https://typerightr.onrender.com
    plan: free

  # Frontend React Service
  - type: web
    name: typerightr
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_SOCKET_URL
        value: https://typerightr-socketio.onrender.com
    plan: free